// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr3lgAcbJBF-Z-v-q2KAuX7pdBkZW_nQ0',
    appId: '1:633573651787:android:0fae23a74d0fdbbd8864ce',
    messagingSenderId: '633573651787',
    projectId: 'instaclone-710e7',
    storageBucket: 'instaclone-710e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzOsne8KChDCrVQuvIblOklZY-UPRy-Cg',
    appId: '1:633573651787:ios:b774c67578bf72cf8864ce',
    messagingSenderId: '633573651787',
    projectId: 'instaclone-710e7',
    storageBucket: 'instaclone-710e7.appspot.com',
    androidClientId: '633573651787-9rrjlpudh8blotu6m8jfaghvfjh1vlph.apps.googleusercontent.com',
    iosClientId: '633573651787-0j6pg969i0dst38h8mtra61lcsr2j179.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone',
  );
}
